CREATE TABLE IF NOT EXISTS ROLES (
    ID SERIAL PRIMARY KEY,
    ROLE VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_TYPES (
    ID SERIAL PRIMARY KEY,
    TYPE VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE USERS (
    ID BIGSERIAL PRIMARY KEY,
    TYPE_ID INT REFERENCES USER_TYPES(ID),
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(250)
);

CREATE TABLE USER_ROLES (
    USER_ID BIGINT REFERENCES USERS(ID),
    ROLE_ID INT REFERENCES ROLES(ID),
    PRIMARY KEY(USER_ID, ROLE_ID)
);

CREATE TABLE IF NOT EXISTS OAUTHS (
    ID BIGSERIAL PRIMARY KEY,
    PROVIDER VARCHAR(25),
    ACCESS_TOKEN VARCHAR(100),
    REFRESH_TOKEN VARCHAR(100),
    EXPIRY BIGINT
);

INSERT INTO
    OAUTHS (PROVIDER, ACCESS_TOKEN, REFRESH_TOKEN, EXPIRY)
VALUES
    ('zoho', '', '', 0);