CREATE TABLE IF NOT EXISTS ROLES (
    ID SERIAL PRIMARY KEY,
    ROLE VARCHAR(100) UNIQUE NOT NULL
);

INSERT INTO ROLES (ROLE)
VALUES
    ('USER_ADMIN'),
    ('USER');

CREATE TABLE IF NOT EXISTS USER_TYPES (
    ID SERIAL PRIMARY KEY,
    TYPE VARCHAR(100) UNIQUE NOT NULL
);

INSERT INTO USER_TYPES (TYPE)
VALUES
    ('User_admin'),
    ('User');

CREATE TABLE USERS (
    ID BIGSERIAL PRIMARY KEY,
    TYPE_ID INT REFERENCES USER_TYPES(ID),
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    PHONE_NUMBER VARCHAR(15) UNIQUE,
    PROFILE_PIC VARCHAR(250),
    PASSWORD VARCHAR(250),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000,
    PASSWORD_RESET_TOKEN VARCHAR(250),
    PASSWORD_RESET_TOKEN_EXPIRY BIGINT
);

INSERT INTO USERS (TYPE_ID, NAME, EMAIL, PHONE_NUMBER, PASSWORD)
VALUES ( 
     1,
    'Sanjay',
    'sanjay@hionstudios.com', 
    '7397541499'
    'password'
);

CREATE TABLE USER_ROLES (
    USER_ID BIGINT REFERENCES USERS(ID),
    ROLE_ID INT REFERENCES ROLES(ID),
    PRIMARY KEY(USER_ID, ROLE_ID)
);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (
     1,
     1
);

CREATE TABLE IF NOT EXISTS OAUTHS (
    ID BIGSERIAL PRIMARY KEY,
    PROVIDER VARCHAR(25),
    ACCESS_TOKEN VARCHAR(100),
    REFRESH_TOKEN VARCHAR(100),
    EXPIRY BIGINT
);

INSERT INTO
    OAUTHS (PROVIDER, ACCESS_TOKEN, REFRESH_TOKEN, EXPIRY)
VALUES
    ('zoho', '', '', 0),
    ('google', '', '', 0),
    ('facebook', '', '', 0);

CREATE TABLE IF NOT EXISTS EVENT_TYPES (
    ID BIGSERIAL PRIMARY KEY,
    TYPE VARCHAR(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS BUDGET_TYPES (
    ID BIGSERIAL PRIMARY KEY,
    TYPE VARCHAR(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS CARPOOL_GUEST_STATUSES (
    ID BIGSERIAL PRIMARY KEY,
    STATUS VARCHAR(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS EVENTS (
    ID BIGSERIAL PRIMARY KEY,
    OWNER_ID BIGINT REFERENCES USERS(ID),
    EVENT_TYPE_ID BIGINT REFERENCES EVENT_TYPES(ID),
    TITLE VARCHAR(250),
    DESCRIPTION TEXT,
    NO_OF_GUEST INT DEFAULT 0,
    DATE_TIME BIGINT,
    START_TIME BIGINT,
    END_TIME BIGINT,
    ADDRESS VARCHAR(300),
    GIFT_SUGGESTION TEXT,
    LOCATION_LATITUDE NUMERIC(10, 7),
    LOCATION_LOGITUDE NUMERIC(10, 7),
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS EVENT_THUMBNAILS (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID),
    IMAGE VARCHAR(250),
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS EVENT_BUDGETS (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID),
    BUDGET_TYPE_ID BIGINT REFEERENCES BUDGET_TYPES(ID),
    DESCRIPTION TEXT,
    AMOUNT BIGINT  
);

CREATE TABLE IF NOT EXISTS EVENT_GUESTS (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID) ON DELETE CASCADE,
    GUEST_ID BIGINT REFERENCES USERS(ID) ON DELETE CASCADE,
    NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(15),
    RSVP VARCHAR(20),
    COMMENT TEXT,
    CARPOOL_EXPECTING BOOLEAN DEFAULT FALSE,
    GUEST_CARPOOL_STATUS BOOLEAN,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000,
    UNIQUE(EVENT_ID, PHONE_NUMBER)
);

CREATE TABLE IF NOT EXISTS CARPOOLS (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID),
    USER_ID BIGINT REFERENCES USERS(ID),
    CAR_NUMBER VARCHAR(20),
    CAR_MODEL VARCHAR(100),
    CAR_COLOR VARCHAR(50),
    AVAILABLE_SEAT INT DEFAULT 0,
    LADIES_ONLY BOOLEAN DEFAULT FALSE,
    START_LOCATION VARCHAR(250),
    END_LOCATION VARCHAR(250),
    START_DATE_TIME BIGINT,
    END_DATE_TIME BIGINT,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS CARPOOL_GUESTS (
    ID BIGSERIAL PRIMARY KEY,
    CARPOOL_ID BIGINT REFERENCES CARPOOLS(ID),
    GUEST_ID BIGINT REFERENCES USERS(ID),
    NAME VARCHAR(100),
    CARPOOL_GUEST_STATUS_ID BIGINT REFERENCES CARPOOL_GUEST_STATUS(ID),
);

CREATE TABLE IF NOT EXISTS CARPOOL_REQUESTS (
    ID BIGSERIAL PRIMARY KEY,
    CARPOOL_ID BIGINT REFERENCES CARPOOLS(ID),
    GUEST_ID BIGINT REFERENCES USERS(ID),
    NO_OF_PEOPLE INT,
    LADIES_ACCOMPANIED BOOLEAN DEFAULT FALSE,
    NOTES TEXT,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000,
    CARPOOL_GUEST_STATUS_ID BIGINT REFERENCES CARPOOL_GUEST_STATUS(ID),
    UNIQUE(CARPOOL_ID, GUEST_ID)
);

CREATE TABLE IF NOT EXISTS EVENT_MESSAGES (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID),
    SENDER_ID BIGINT REFERENCES USERS(ID),
    MESSAGE TEXT,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS EVENT_MESSAGE_READS (
    ID BIGSERIAL PRIMARY KEY,
    MESSAGE_ID BIGINT REFERENCES EVENT_MESSAGES(ID),
    RECEIPIENT_ID BIGINT REFERENCES USERS(ID) ON DELETE CASCADE,
    READ_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000,
    UNIQUE(MESSAGE_ID, RECEIPIENT_ID)
);

CREATE TABLE IF NOT EXISTS NOTIFICATION_TYPES (
    ID BIGSERIAL PRIMARY KEY,
    TYPE VARCHAR(100) UNIQUE
)

INSERT INTO NOTIFICATION_TYPES (TYPE)
VALUES
    ('Rspv'),
    ('Carpool'),
    ('Event'),
    ('Admin');

CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID BIGSERIAL PRIMARY KEY,   
    USER_ID BIGINT REFERENCES USERS(ID),
    NOTIFICATION_TYPE_ID BIGINT REFERENCES NOTIFICATION_TYPES(ID),
    CONTENT VARCHAR(100),
    IS_READ BOOLEAN DEFAULT FALSE,
    HREF VARCHAR(100),
    TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS EVENT_TODO_LIST (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID) ON DELETE CASCADE,
    TODO TEXT NOT NULL,
    STATUS BOOLEAN DEFAULT FALSE,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS BACKUPS (
    ID BIGSERIAL PRIMARY KEY,
    BACKUP_FILE VARCHAR(100) UNIQUE,
    BACKUP_DATE BIGINT
);