CREATE TABLE IF NOT EXISTS ROLES (
    ID SERIAL PRIMARY KEY,
    ROLE VARCHAR(100) UNIQUE NOT NULL
);

INSERT INTO ROLES (ROLE)
VALUES
    ('IINVITE_ADMIN'),
    ('ORGANISER');

CREATE TABLE IF NOT EXISTS USER_TYPES (
    ID SERIAL PRIMARY KEY,
    TYPE VARCHAR(100) UNIQUE NOT NULL
);

INSERT INTO USER_TYPES (TYPE)
VALUES
    ('Iinvite'),
    ('Organiser');

CREATE TABLE USERS (
    ID BIGSERIAL PRIMARY KEY,
    TYPE_ID INT REFERENCES USER_TYPES(ID),
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    PHONE_NUMBER VARCHAR(15) UNIQUE,
    PASSWORD VARCHAR(250),
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000,
    PASSWORD_RESET_TOKEN VARCHAR(250),
    PASSWORD_RESET_TOKEN_EXPIRY BIGINT
);

INSERT INTO USERS (TYPE_ID, NAME, EMAIL, PHONE_NUMBER, PASSWORD)
VALUES ( 
     1,
    'Sanjay',
    'sanjay@hionstudios.com', 
    '7397541499'
    'password'
);

CREATE TABLE USER_ROLES (
    USER_ID BIGINT REFERENCES USERS(ID),
    ROLE_ID INT REFERENCES ROLES(ID),
    PRIMARY KEY(USER_ID, ROLE_ID)
);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (
     1,
     1
);

CREATE TABLE IF NOT EXISTS OAUTHS (
    ID BIGSERIAL PRIMARY KEY,
    PROVIDER VARCHAR(25),
    ACCESS_TOKEN VARCHAR(100),
    REFRESH_TOKEN VARCHAR(100),
    EXPIRY BIGINT
);

INSERT INTO
    OAUTHS (PROVIDER, ACCESS_TOKEN, REFRESH_TOKEN, EXPIRY)
VALUES
    ('zoho', '', '', 0),
    ('google', '', '', 0),
    ('facebook', '', '', 0);

CREATE TABLE IF NOT EXISTS SUBSCRIPTION_TYPES (  
    ID BIGSERIAL PRIMARY KEY,
    TYPE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS EVENT_TYPES (
    ID BIGSERIAL PRIMARY KEY,
    TYPE VARCHAR(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS BUDGET_TYPES (
    ID BIGSERIAL PRIMARY KEY,
    TYPE VARCHAR(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS CARPOOL_GUEST_STATUS (
    ID BIGSERIAL PRIMARY KEY,
    STATUS VARCHAR(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS SUBSCRIPTIONS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES USERS(ID),
    SUBSCRIPTION_TYPE_ID BIGINT REFERENCES SUBSCRIPTION_TYPES(ID),
    START_DATE BIGINT, 
    EXPIRY_DATE BIGINT,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000,
    UPDATED_TIME BIGINT,
    ISACTIVE BOOLEAN DEFAULT 'TRUE'
);

CREATE TABLE IF NOT EXISTS ORGANISERS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFEERENCES USERS(ID),
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    PHONE_NUMBER VARCHAR(15) UNIQUE,
    PROFILE_PIC VARCHAR(250),
    SUBSCRIPTION_ID BIGINT REFEERENCES SUBSCRIPTIONS(ID),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
);

CREATE TABLE IF NOT EXISTS EVENTS (
    ID BIGSERIAL PRIMARY KEY,
    ORGANISER_ID BIGINT REFERENCES ORGANISERS(ID),
    EVENT_TYPE_ID BIGINT REFERENCES EVENT_TYPES(ID),
    TITLE VARCHAR(250),
    DESCRIPTION TEXT,
    NO_OF_GUEST INT DEFAULT 0,
    DATE_TIME BIGINT,
    START_TIME BIGINT,
    END_TIME BIGINT,
    ADDRESS VARCHAR(300),
    LOCATION_LATITUDE DOUBLE PRECISION,
    LOCATION_LOGITUDE DOUBLE PRECISION,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS EVENT_THUMBNAILS (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID),
    IMAGE VARCHAR(250),
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS EVENT_BUDGETS (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID),
    BUDGET_TYPE_ID BIGINT REFEERENCES BUDGET_TYPES(ID),
    DESCRIPTION TEXT,
    AMOUNT BIGINT,   
);

CREATE TABLE IF NOT EXISTS EVENT_GUESTS (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID),
    NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(15) UNIQUE,
    RSVP VARCHAR(20),
    COMMENT TEXT,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS CARPOOLS (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID),
    ORGANISER_ID BIGINT REFERENCES ORGANISERS(ID),
    AVAILABLE_SEAT INT DEFAULT 0,
    LADIES_ONLY BOOLEAN DEFAULT FALSE,
    START_LOCATION VARCHAR(250),
    END_LOCATION VARCHAR(250),
    START_DATE_TIME BIGINT,
    END_DATE_TIME BIGINT,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS CARPOOL_GUESTS (
    ID BIGSERIAL PRIMARY KEY,
    CARPOOL_ID BIGINT REFERENCES CARPOOLS(ID),
    USER_ID BIGINT REFERENCES USERS(ID),
    NAME VARCHAR(100),
    CARPOOL_GUEST_STATUS_ID BIGINT REFERENCES CARPOOL_GUEST_STATUS(ID),
);

CREATE TABLE IF NOT EXISTS EVENT_MESSAGES (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID),
    SENDER_ID BIGINT REFERENCES USERS(ID),
    MESSAGE TEXT,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS EVENT_MESSAGE_READS (
    ID BIGSERIAL PRIMARY KEY,
    MESSAGE_ID BIGINT REFERENCES EVENT_MESSAGES(ID),
    USER_ID BIGINT REFERENCES USERS(ID) ON DELETE CASCADE,
    READ_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000,
    UNIQUE(MESSAGE_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS NOTIFICATION_TYPES (
    ID BIGSERIAL PRIMARY KEY,
    TYPE VARCHAR(100) UNIQUE
)

INSERT INTO NOTIFICATION_TYPES (TYPE)
VALUES
    ('Rspv'),
    ('Carpool'),
    ('Event'),
    ('Admin');

CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID BIGSERIAL PRIMARY KEY,   
    USER_ID BIGINT REFERENCES USERS(ID),
    NOTIFICATION_TYPE_ID BIGINT REFERENCES NOTIFICATION_TYPES(ID),
    CONTENT VARCHAR(100),
    IS_READ BOOLEAN DEFAULT FALSE,
    HREF VARCHAR(100),
    TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS EVENT_TODO_SHEETS (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_ID BIGINT REFERENCES EVENTS(ID) ON DELETE CASCADE,
    TITLE VARCHAR(250),
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000,
);

CREATE TABLE IF NOT EXISTS EVENT_TODO_LIST (
    ID BIGSERIAL PRIMARY KEY,
    EVENT_TODO_SHEET_ID BIGINT REFERENCES EVENT_TODO_SHEETS(ID) ON DELETE CASCADE,
    TODO TEXT NOT NULL,
    STATUS BOOLEAN DEFAULT FALSE,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);

CREATE TABLE IF NOT EXISTS BACKUPS (
    ID BIGSERIAL PRIMARY KEY,
    BACKUP_FILE VARCHAR(100) UNIQUE,
    BACKUP_DATE BIGINT
);

CREATE TABLE IF NOT EXISTS PAYMENT_ORDERS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES USERS(ID),
    USER_TYPE_ID BIGINT REFERENCES USER_TYPES(ID),
    AMOUNT BIGINT,
    TRANSACTION_ID VARCHAR(100) UNIQUE,
    CREATED_TIME BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000,
    UPDATED_TIME BIGINT,
    STATUS BOOLEAN
);